echo sparsity $1 block_size $2 $3
python prune_hubert_baseline.py \
        --model_name_or_path hubert_pretrained_ck \
        --dataset_name superb \
        --dataset_config_name ks \
        --output_dir hubert_ks_finetune_${1}_block_${2}_${3} \
        --overwrite_output_dir \
        --remove_unused_columns False \
        --do_train --eval_split_name test --learning_rate 1e-3 \
        --max_length_seconds 1 \
        --warmup_ratio 0.1 \
        --num_train_epochs 200 \
        --per_device_train_batch_size 32 \
        --gradient_accumulation_steps 4 \
        --per_device_eval_batch_size 32 \
        --dataloader_num_workers 12 \
        --logging_strategy steps \
        --logging_steps 10 \
        --evaluation_strategy epoch \
        --save_strategy epoch \
        --load_best_model_at_end True \
        --save_total_limit 3 \
        --seed 0 \
        --lr_scheduler_type cosine \
        --blockh $2 \
        --blockw $3 \
        --sparsity_ratio $1